version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(message)s" #Log format
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "fileName": %(filename)s, "lineNumber": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout
loggers:
  root: # This is a default setting for loggers. you can use consle and file handler as default handlers.
    level: DEBUG
    handlers: [console]
    propagate: no
